version: '3.9'

services:

  db:
    container_name: postgres-shop
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
#      - /home/atf/db/shop-postgres:/var/lib/postgresql/data
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    ports:
      - "8082:8080"
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: pass

volumes:
  postgres-volume:
